=== EdwardAdelin/SeWebHW1/recipe-app/recipe-app/src/main/resources/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="users">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="surname" type="xs:string"/>
                                        <xs:element name="skill" type="xs:string"/>
                                        <xs:element name="preferredCuisine" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="recipes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="recipe" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="cuisines">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cuisine" type="xs:string" minOccurs="2" maxOccurs="2"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="difficulty">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Beginner"/>
                                                    <xs:enumeration value="Intermediate"/>
                                                    <xs:enumeration value="Advanced"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EdwardAdelin/SeWebHW1/recipe-app/recipe-app/src/main/resources/xml/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="schema.xsd">
   <users>
      <user>
         <name>Ade</name>
         <surname>Smith</surname>
         <skill>Intermediate</skill>
         <preferredCuisine>Romanian</preferredCuisine>
      </user>
      <user>
         <name>John</name>
         <surname>Doe</surname>
         <skill>Beginner</skill>
         <preferredCuisine>Italian</preferredCuisine>
      </user>
      <user>
         <name>hade</name>
         <surname>Smith</surname>
         <skill>Intermediate</skill>
         <preferredCuisine>Asian</preferredCuisine>
      </user>
   </users>
   <recipes>
      <recipe>
         <title>Creamy pumpkin pasta</title>
         <cuisines>
            <cuisine>Mediterranean</cuisine>
            <cuisine>Italian</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Sausage, mustard &amp; apple hash</title>
         <cuisines>
            <cuisine>Mediterranean</cuisine>
            <cuisine>French</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Mushroom stroganoff</title>
         <cuisines>
            <cuisine>Asian</cuisine>
            <cuisine>French</cuisine>
         </cuisines>
         <difficulty>Intermediate</difficulty>
      </recipe>
      <recipe>
         <title>Beetroot &amp; feta pasta</title>
         <cuisines>
            <cuisine>Indian</cuisine>
            <cuisine>Mexican</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Pork &amp; apple burgers</title>
         <cuisines>
            <cuisine>French</cuisine>
            <cuisine>Mediterranean</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Mushroom soup</title>
         <cuisines>
            <cuisine>Asian</cuisine>
            <cuisine>Indian</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Squash &amp; halloumi flatbreads with sweet chilli beetroot jam</title>
         <cuisines>
            <cuisine>Italian</cuisine>
            <cuisine>Asian</cuisine>
         </cuisines>
         <difficulty>Beginner</difficulty>
      </recipe>
      <recipe>
         <title>Simple squash risotto</title>
         <cuisines>
            <cuisine>French</cuisine>
            <cuisine>Asian</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Slow cooker spiced root &amp; lentil casserole</title>
         <cuisines>
            <cuisine>Mexican</cuisine>
            <cuisine>French</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Squash &amp; spinach fusilli with pecans</title>
         <cuisines>
            <cuisine>Mediterranean</cuisine>
            <cuisine>French</cuisine>
         </cuisines>
         <difficulty>Intermediate</difficulty>
      </recipe>
      <recipe>
         <title>Easy vegetable curry</title>
         <cuisines>
            <cuisine>Mexican</cuisine>
            <cuisine>Asian</cuisine>
         </cuisines>
         <difficulty>Intermediate</difficulty>
      </recipe>
      <recipe>
         <title>Sausage &amp; butternut squash shells</title>
         <cuisines>
            <cuisine>Indian</cuisine>
            <cuisine>Italian</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Autumn vegetable soup with cheesy toasts</title>
         <cuisines>
            <cuisine>Mexican</cuisine>
            <cuisine>French</cuisine>
         </cuisines>
         <difficulty>Intermediate</difficulty>
      </recipe>
      <recipe>
         <title>Mushroom &amp; sausage pasta</title>
         <cuisines>
            <cuisine>Italian</cuisine>
            <cuisine>Mexican</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Creamy pumpkin &amp; lentil soup</title>
         <cuisines>
            <cuisine>Mexican</cuisine>
            <cuisine>Italian</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Curried parsnip soup</title>
         <cuisines>
            <cuisine>French</cuisine>
            <cuisine>Mediterranean</cuisine>
         </cuisines>
         <difficulty>Intermediate</difficulty>
      </recipe>
      <recipe>
         <title>Red onion gravy</title>
         <cuisines>
            <cuisine>French</cuisine>
            <cuisine>Mediterranean</cuisine>
         </cuisines>
         <difficulty>Beginner</difficulty>
      </recipe>
      <recipe>
         <title>Butternut squash pilaf</title>
         <cuisines>
            <cuisine>Italian</cuisine>
            <cuisine>Indian</cuisine>
         </cuisines>
         <difficulty>Advanced</difficulty>
      </recipe>
      <recipe>
         <title>Sausage &amp; maple swede traybake</title>
         <cuisines>
            <cuisine>Italian</cuisine>
            <cuisine>Mexican</cuisine>
         </cuisines>
         <difficulty>Beginner</difficulty>
      </recipe>
      <recipe>
         <title>Cauliflower mac &amp; cheese</title>
         <cuisines>
            <cuisine>Asian</cuisine>
            <cuisine>Indian</cuisine>
         </cuisines>
         <difficulty>Beginner</difficulty>
      </recipe>
      <recipe>
         <title>Sarmale</title>
         <cuisines>
            <cuisine>Turkish</cuisine>
            <cuisine>Romanian</cuisine>
         </cuisines>
         <difficulty>Intermediate</difficulty>
      </recipe>
   </recipes>
</data>
